# smb.conf — SAMBA01 (192.168.10.20)
# Serveur de fichiers intégré au domaine PME.LOCAL
# Auteur : mustapha

[global]
    workgroup               = PME
    realm                   = PME.LOCAL
    server string           = SAMBA01 - Serveur de fichiers PME
    security                = ADS
    encrypt passwords       = yes
    kerberos method         = secrets and keytab

    # Winbind
    winbind use default domain = yes
    winbind enum users      = yes
    winbind enum groups     = yes
    winbind separator       = +

    # Mapping d'ID
    idmap config * : backend  = tdb
    idmap config * : range    = 1000-9999
    idmap config PME : backend = rid
    idmap config PME : range   = 10000-99999

    # Templates
    template shell          = /bin/bash
    template homedir        = /home/%D/%U

    # ACL
    vfs objects             = acl_xattr
    map acl inherit         = yes
    store dos attributes    = yes

    # Logs
    log file                = /var/log/samba/%m.log
    log level               = 1
    max log size            = 50

    # Réseau
    interfaces              = 192.168.10.20/24 lo
    bind interfaces only    = yes

    # Désactiver les protocoles anciens
    server min protocol     = SMB2
    ntlm auth               = no


[direction]
    comment                 = Partage réservé à la Direction
    path                    = /srv/shares/direction
    valid users             = @"PME+GRP-Direction"
    read only               = no
    browsable               = yes
    create mask             = 0660
    directory mask          = 0770
    force create mode       = 0660
    force directory mode    = 0770


[tech]
    comment                 = Partage réservé au département Tech
    path                    = /srv/shares/tech
    valid users             = @"PME+GRP-Tech"
    read only               = no
    browsable               = yes
    create mask             = 0660
    directory mask          = 0770
    force create mode       = 0660
    force directory mode    = 0770


[commercial]
    comment                 = Partage réservé au département Commercial
    path                    = /srv/shares/commercial
    valid users             = @"PME+GRP-Commercial"
    read only               = no
    browsable               = yes
    create mask             = 0660
    directory mask          = 0770
    force create mode       = 0660
    force directory mode    = 0770


[commun]
    comment                 = Partage commun à tous les employés
    path                    = /srv/shares/commun
    valid users             = @"PME+GRP-Direction" @"PME+GRP-Tech" @"PME+GRP-Commercial"
    read only               = no
    browsable               = yes
    create mask             = 0664
    directory mask          = 0775
